import os
from github import Auth, Github, GithubException

# Load token from backend/.env if not in os.environ
token = os.environ.get("GITHUB_TOKEN", "")
if not token and os.path.exists(".env"):
    with open(".env") as f:
        for line in f:
            if line.startswith("GITHUB_TOKEN="):
                token = line.strip().split("=", 1)[1]
                break

if not token and os.path.exists("backend/.env"):
    with open("backend/.env") as f:
        for line in f:
            if line.startswith("GITHUB_TOKEN="):
                token = line.strip().split("=", 1)[1]
                break

print("Testing GitHub token...")
if not token:
    print("No GITHUB_TOKEN found!")
    exit(1)

g = Github(auth=Auth.Token(token))
user = g.get_user()
print("Authenticated GitHub User:", user.login)

repo = g.get_repo("dhanushkumar-amk/CODEGUARD---NVIDIA-HACKTHON-PROJECT")
print("Repo full name:", repo.full_name)
print("Default branch:", repo.default_branch)
print("Permissions:", repo.permissions)

# Check if branch codeguard-fixes-rehearsal can be created
branch_name = "codeguard-rehearsal-test"
base_sha = repo.get_branch(repo.default_branch).commit.sha

try:
    ref = repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
    print(f"Created test branch: {branch_name} (sha: {base_sha[:8]})")
    
    # Create or update a test remediation commit
    test_file_path = "docs/remediation-proof.md"
    content = "# CodeGuard Automated Remediation Proof\nVerified a11y patch committed by CodeGuard agent.\n"
    
    commit_res = repo.create_file(
        path=test_file_path,
        message="fix(a11y): automated accessibility remediation by CodeGuard",
        content=content,
        branch=branch_name,
    )
    print("Committed file to branch:", commit_res["commit"].sha[:8])
    
    # Open real PR
    pr = repo.create_pull(
        title="CodeGuard: Automated Accessibility Remediation (Rehearsal)",
        body="## Accessibility Remediation PR\n\nThis pull request was automatically generated by CodeGuard during Phase 28 rehearsal testing.\n\n- **Target Repo**: " + repo.full_name + "\n- **Agent**: CodeGuard NVIDIA Nemotron Remediation Pipeline\n- **Status**: Verified in sandbox\n",
        head=branch_name,
        base=repo.default_branch,
    )
    print(f"\nSUCCESS! Real Pull Request Created:")
    print(f"PR URL: {pr.html_url}")
    print(f"PR Number: #{pr.number}")

except GithubException as ge:
    print("GitHub Exception:", ge.status, ge.data)
