"""
Fix Router: Endpoints to inspect synthesized remediation patches generated by Nemotron Ultra.
"""
from typing import List
from fastapi import APIRouter
from app.models.schemas import ProposedFix
from app.state import get_scan

router = APIRouter(tags=["Remediation"])


@router.get(
    "/{scan_id}",
    response_model=List[ProposedFix],
    summary="Get proposed remediation fixes for a scan",
)
async def get_fixes_for_scan(scan_id: str) -> List[ProposedFix]:
    """
    Retrieve all synthesized code patches and unified diffs generated for this scan.
    """
    scan = get_scan(scan_id)
    return scan.get("fixes", [])
